# Generated by Django 2.0.8 on 2018-10-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_user', '0004_auto_20181015_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtransaction',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active?'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_whatsapp',
            field=models.BooleanField(default=False, verbose_name='Is mobile WhatsApp enabled?'),
        ),
    ]
