# Generated by Django 2.0.8 on 2018-10-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_user', '0005_auto_20181015_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpvalidation',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create Date'),
        ),
        migrations.AlterField(
            model_name='otpvalidation',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Modified'),
        ),
    ]
